import os
import sqlite3

import psycopg


SQLITE_DATABASE = os.path.join(
    os.path.dirname(os.path.abspath(__file__)),
    "data.db"
)

SCHEMA = """
CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'student'
        CHECK (role IN ('teacher', 'student')),
    total_points INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sections (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS vocabulary (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_id INTEGER NOT NULL REFERENCES sections(id) ON DELETE CASCADE,
    chinese TEXT NOT NULL,
    pinyin TEXT,
    translation TEXT NOT NULL,
    relevance INTEGER NOT NULL DEFAULT 1 CHECK (relevance > 0),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS game_results (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    section_id INTEGER NOT NULL REFERENCES sections(id) ON DELETE CASCADE,
    vocabulary_id INTEGER NOT NULL REFERENCES vocabulary(id) ON DELETE CASCADE,
    correct INTEGER NOT NULL DEFAULT 0 CHECK (correct IN (0, 1)),
    points INTEGER NOT NULL DEFAULT 0,
    played_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
"""


def rows(table, columns):
    connection = sqlite3.connect(SQLITE_DATABASE)
    connection.row_factory = sqlite3.Row
    values = connection.execute(
        f"SELECT {', '.join(columns)} FROM {table} ORDER BY id"
    ).fetchall()
    connection.close()
    return values


def migrate():
    database_url = os.environ.get("DATABASE_URL")
    if not database_url:
        raise RuntimeError("DATABASE_URL is not configured")

    with psycopg.connect(database_url) as database:
        with database.cursor() as cursor:
            cursor.execute(SCHEMA)

            for table, columns in {
                "users": (
                    "id", "username", "password_hash", "role",
                    "total_points", "created_at"
                ),
                "sections": (
                    "id", "title", "description", "created_at", "updated_at"
                ),
                "vocabulary": (
                    "id", "section_id", "chinese", "pinyin",
                    "translation", "relevance", "created_at"
                ),
                "game_results": (
                    "id", "user_id", "section_id", "vocabulary_id",
                    "correct", "points", "played_at"
                )
            }.items():
                column_list = ", ".join(columns)
                placeholders = ", ".join("%s" for _ in columns)
                for row in rows(table, columns):
                    cursor.execute(
                        f"INSERT INTO {table} ({column_list}) "
                        f"VALUES ({placeholders}) ON CONFLICT (id) DO NOTHING",
                        tuple(row[column] for column in columns)
                    )

            for table in ("users", "sections", "vocabulary", "game_results"):
                cursor.execute(
                    f"SELECT setval(pg_get_serial_sequence('{table}', 'id'), "
                    f"COALESCE((SELECT MAX(id) FROM {table}), 1), true)"
                )

    print("SQLite-Daten wurden nach PostgreSQL migriert.")


if __name__ == "__main__":
    migrate()
